seed: 42
map_size: [64, 32]
room_size: [[5, 5], [11, 11]]
n_rooms: 7
connection_prob: 0.75
wall_prob: 0.5
empty_tile: 0
ground_tile: 1
wall_tile: 2

window_width: 1280
window_height: 720
total_lives: 5

expression_window: 5
expressions: ['Happy', 'Sad', 'Fear', 'Disgust', 'Surprise', 'Angry', 'Neutral']